### ISSUE TITLE
2.0?

### ISSUE THREAD

**Issue by 11111000000** [zaceno/hyperapp-nestable#10]

**Comment by zaceno** [comment]
You mean a version compatible with hyperapp v2? Yeah I’ve been thinking about it and toying with some alternative approaches.

**Comment by 11111000000** [comment]
What approaches?

**Comment by zaceno** [comment]
Nothing solid yet. I'm not terribly invested in having stateful components in hyperapp any longer (it's too "against the grain", and I'd prefer to find more harmonious methods of modularization first) - so it's mostly out of academic curiosity I've experimented.

I've tried emulating lifecycle events, in order to use a similar design as hyperapp-nestable currently has. Also wrapping apps in custom elements, with subs/fx for intercom between custom elements. And I'm just now toying with the idea of keeping component state in the main state transparently, via middleware & HOF.

If I arrive at something that seems solid & dependable I'll make sure to publish a new 2.0.
