### ISSUE TITLE
Children?

### ISSUE THREAD

**Issue by zaceno** [zaceno/hyperapp-nestable#2]
Should nestable components be allowed to have children. And how should it be supported?

What are the use cases? What are the requirements?

**Comment by jonlovera** [comment]
@zaceno Children's and props should work like they do on hyperapp. Nestable should allow you to have separate states and actions on your component which is what it doe. However, currently, any props that you pass to the component will be added to the state and props should be totally different than the state.

That's why in hyperapp we do it like this. It should be the same for nestable.
```
(state, actions) => (props, children) => { ...... }
```

Use case, for example, is that you want to have a form component which saves all the inputs into state for you and send them back to the onSubmit function. I created the example.
https://gist.github.com/jonlov/21021db1ae7e05ca8a475da67d898595

**Comment by zaceno** [comment]
@jonlov Nice example! I agree, that would be more elegant! It makes interoperability with the props passed from the outside a bit more cumbersome, but since the model itself is more elegant, I think that won't be a problem. 

I'll be pushing an update soon!

Now that we'll basically have stateful components that can have children, we'll want some way to pass data from a stateful parent component to child components. React does this with "context", and so I think next I'll look into bundling context-enabled nestable components with my context-enabling HOA `hyperapp-context`. Then you'll be able to basically port a React app to hyperapp without needing to rearchitect the thing. (You'll need to rewrite essentially everything, but I mean: you can use the same architecture)

...but I digress 😄 ! Don't worry -- I'll leave this repo/package as a non-context-enabled simpler package for those who just want stateful components and don't care about context.

**Comment by zaceno** [comment]
Ok, I published `hyperapp-nestable@1.0.0`  with the signature you suggested.

`(state, actions) => (props, children) => VNode`

But if your view doesn't care about props or children `(state, actions) => VNode` works as well. 

Now, in order to make interoperability with the outside app a little easier, the `init` action (if you use it)  will be passed the props. So you can pass callbacks to the component that way.

**Comment by zaceno** [comment]
Thanks a lot for the great suggestion @jonlov!! 🎉

**Comment by jonlovera** [comment]
@zaceno Thank you very much for that update! I need it, awesome plugin 😃
